### ISSUE TITLE
Add data-form-type ignore guideline

### ISSUE THREAD

**Issue by therealglazou** [Dashlane/SAWF#1]
The title says it all. Add a guideline about `data-form-type="other"` as a "ignore" mechanism.

**Comment by sybrew** [comment]
What happened to the unanimously agreed upon and ubiquitous HTML `<form>`/`<input>` standard attribute `autocomplete=off`? 
Developers around the world shouldn't have to bend over forward to abide by your arbitrary standard, which, to be frank, doesn't even work as intended.

**Comment by sybrew** [comment]
Hi Daniel, someone else has the same question, please fix https://stackoverflow.com/questions/59939931/stop-dashlane-auto-fill-on-specific-input-fields#comment124692688_69190988.

**Comment by Mikescops** [comment]
Hello,

While you should mind your attitude in public spaces, here is an answer from the team building the autofill at Dashlane.

We used to support the autocomplete attribute, however our experience over the years has shown that it is badly used on numerous websites. As it was disrupting our autofill very often, we decided to ignore it. Note that most browsers also ignore it for login fields.
About the StackOverflow issue you're referring to, Dashlane users can now disable autofill on a specific field using our right click menu.

I'm locking the thread for further comments, please open a new issue to submit a bug or request.
