### ISSUE TITLE
Multi-step form issue

### ISSUE THREAD

**Issue by Siddharth227** [Dashlane/SAWF#10]
We have a three step form to reset password if user forgets.
Login screen (click on forgot password) -> User verification form (enters username and other data) -> Authentication form (OTP etc.,) -> Password reset form (New and confirm new password).

In this flow, when we enter the new password, dashlane prompts(chrome extension) to store password but the login/username remains unpopulated.

**Comment by kolakolak** [comment]
Hi,
Again, I apologize for the delayed response. Don't hesitate to contact our customer support for this issue as well.
