### ISSUE TITLE
Angular Routes closing the dashlane pop-up

### ISSUE THREAD

**Issue by Siddharth227** [Dashlane/SAWF#12]
We have a page where a button click routes to new page using angular routes. The first page has change password form and when we click on submit button, the pop-up comes up.
Before entering the username and savin, the pop-up is disappearing once the angular route loads up. Please advice.

**Comment by kolakolak** [comment]
Hello,
My apologies for the very delayed response. If you're still experiencing the issue, please contact [Dashlane's customer support](https://support.dashlane.com/hc/en-us) with a link to your website and all the details of your issue. 
Thank you!
