### ISSUE TITLE
Does Dashlane's browser extension follow this spec?

### ISSUE THREAD

**Issue by warpech** [Dashlane/SAWF#13]
I appreciate your effort to write a spec for enhancing the semantics of Web forms used by Web extensions such as Dashlane, as opposed to just publishing it in form of API reference for the browser extension. Thanks! However, I have a question:

The spec says:

> The `data-form-type` attribute carries type information about the form carrying the attribute. It is an unordered list of comma-separated case-insensitive values. Its default value is `"other"`. 

I have noticed in my web app that the Dashlane browser extension to Chrome adds its autocompletion to a regular `<input type="text">` without a `data-form-type` attribute.

Does it mean that Dashlane web extension does not follow the spec closely, or should the spec be updated?

If needed, I can provide the actual code that triggered the extension by email.

**Comment by kolakolak** [comment]
Hi, thanks a lot for your feedback!

You don't necessarily need to add a `data-form-type` attribute to your code for our autofill to work: our engine will do it for you after analyzing the page. The spec is just here if you want to ensure we autofill the right information (and if you want to speed up the analysis process).

However, after the analysis is done (it takes milliseconds), if you see an `input type="text"` without a `data-form-type` being autofilled, this is very strange and not supposed to happen... I would be very interested in having a look at your code then!

**Comment by Mikescops** [comment]
Closing this, feel free to reopen if you have any other feedback.
